# Generated by Django 3.1.3 on 2020-11-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('round_robin', 'round_robin'), ('lowest_ping_time', 'lowest_ping_time'), ('lowest_cpu_usage', 'lowest_cpu_usage')], default='round_robin', max_length=20)),
                ('name', models.CharField(max_length=15)),
                ('request_counter', models.IntegerField(default=0)),
                ('last_round_server_id', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15)),
                ('cpu_state', models.FloatField(default=0.5)),
                ('ping_time', models.FloatField(default=9999.0)),
                ('analysis_method', models.CharField(choices=[('ping', 'ping'), ('cpu', 'cpu')], default='ping', max_length=4)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.service')),
            ],
        ),
    ]
