# Generated by Django 3.1.4 on 2020-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='analysis_method',
        ),
        migrations.AlterField(
            model_name='server',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
